### ISSUE TITLE
Can't input new IP address for GMSEC server

### ISSUE THREAD

**Issue by Brandon-Scott-JHUAPL** [nasa/Mixed-Reality-Exploration-Toolkit#7]
On MRET21.1.1VR, there seems to be an issue entering an IP address of the GMSEC server within the input field on the collaboration tab of the menu.  This has been tested on two separate computers with an Oculus Quest 2 (Air Link) and an HTC Vive.

**Comment by dzbaker** [comment]
Which menu are you working in (is it the one you bring up from the controller)?

**Comment by Brandon-Scott-JHUAPL** [comment]
Yes.  That's the one.

**Comment by dzbaker** [comment]
Interesting. I may want to ask you to demonstrate it for me, I seem to get different behavior.

**Comment by dzbaker** [comment]
Closing issue as it turns out to be a bug with the input system for Oculus/knuckles controllers. Tom will create issue for that.
